# Generated by Django 4.1.7 on 2023-04-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='user',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='Status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='Team_Contact',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='Team_Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='Team_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectteam',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
