# Generated by Django 4.1.7 on 2023-04-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_remove_projectteam_user_projectteam_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='Team_Contact',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='Team_Email',
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='Team_Name',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
