# Generated by Django 4.1.7 on 2023-04-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_projectteam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AlterModelTable(
            name='projectteam',
            table='detail_project',
        ),
    ]
