# Generated by Django 4.1.7 on 2023-04-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectteam_project_alter_projectteam_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectteam',
            table='project_team',
        ),
    ]
