# Generated by Django 4.1.7 on 2023-04-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_status_project_tatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tatus',
            new_name='status',
        ),
    ]
