# Generated by Django 4.1.7 on 2023-04-09 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_badge_project_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Team',
            new_name='Project_Team_Module',
        ),
    ]
